### ISSUE TITLE
memory in-efficent?

### ISSUE THREAD

**Issue by chocolocked** [twitter-research/tgn#16]
Hi I was testing this model for link prediction on  my own dataset: PubMed co-author; and when I specified to augment the model with node memory, it couldn't even run with a batch size of 5? And when  'not using the memory',  the whole model works. Based on what I've read in your paper, the memory is where the performance really made a difference. and sorry I'm really new to graph neural networks, but am I missing anything or just the model is extremely inefficient?

**Comment by emalgorithm** [comment]
Hi @chocolocked,

I wouldn't know about the specifics of your case, but while the model is in theory very scalable, the current implementation in this repo loads the whole model memory into GPU memory, which does not scale and causes OOM errors if the graph has too many nodes. This can be solved by keeping the model memory in CPU memory, and only loading to GPU memory the memory for the nodes that are used in each batch (as you would for their features).

I hope that answers your question.

**Comment by Aliounegahn** [comment]
Hi @emalgorithm @chocolocked , 

i am running the self supervised nn in order to extract the temporal embeddings of the users and i am currently facing the same issue. My dataset has the same input format, but the graph is quite large (+8 millions of nodes and +60 millions interactions). Any guidance on how to achieve this please ? thanks for your help :)
