### ISSUE TITLE
Time comparison for the key operations of TGN on IPU and GPU with different batch sizes

### ISSUE THREAD

**Issue by ayasar70** [twitter-research/tgn#21]
Hello,

I have a couple of questions about the [plot](https://miro.medium.com/max/504/0*gmXGRalaeLMpQKNm) from Bronsteins et al.'s "Accelerating and scaling Temporal Graph Networks on the Graphcore IPU" article:

1- How did you separate and measure those components?
2- Is there a script for that experiment?

Kind regards.

**Comment by emalgorithm** [comment]
Hi, the throughput numbers were acquired using the code [here](https://github.com/graphcore/examples/tree/v3.0.0/gnn/tgn/tensorflow1). End-to-end throughput by just running the model, the individual ops with micro-benchmarks that just execute the specific bit with a large number of on-device iterations to negate any latency that is due to I/O.
Unfortunately the exact micro benchmark scripts are not in the repo and won’t be added since GraphCore deprecated Tensorflow1 for IPU (but it should still run with older SDKs.) 

There is also a more recent pytorch implementation at https://github.com/graphcore/examples/tree/master/gnn/tgn/pytorch
